import Link from "next/link";
import WidgetContainer from "@/components/widget/WidgetContainer";

export default function Home() {
  return (
    <div className="flex flex-col min-h-screen font-sans bg-zinc-50 dark:bg-black text-black dark:text-white">
      {/* Header */}
      <header className="w-full flex justify-between items-center py-6 px-8 border-b border-zinc-200 dark:border-zinc-800">
        <h1 className="text-2xl font-bold tracking-tight">Smile Forward</h1>
        <div className="flex gap-4">
          <Link 
            href="/admin/dashboard" 
            className="px-4 py-2 text-sm font-medium bg-zinc-900 text-white dark:bg-white dark:text-black rounded-md hover:opacity-90 transition-opacity"
          >
            Admin Panel
          </Link>
          <Link 
            href="/widget" 
            className="px-4 py-2 text-sm font-medium border border-zinc-300 dark:border-zinc-700 rounded-md hover:bg-zinc-100 dark:hover:bg-zinc-900 transition-colors"
          >
            Standalone Widget
          </Link>
        </div>
      </header>

      <main className="flex-1 flex flex-col items-center justify-start p-8 md:p-12 gap-12">
        {/* Intro Section */}
        <section className="text-center max-w-2xl space-y-4">
          <h2 className="text-4xl md:text-5xl font-extrabold tracking-tight bg-gradient-to-r from-blue-600 to-teal-500 bg-clip-text text-transparent">
            Transform Your Smile with AI
          </h2>
          <p className="text-lg text-zinc-600 dark:text-zinc-400">
            Smart Smile Analysis & Simulation. Start the journey to your perfect smile today.
            <br className="hidden md:block"/>
            Upload a photo below to see the magic.
          </p>
        </section>

        {/* Demo Widget Section */}
        <section className="w-full max-w-3xl border border-zinc-200 dark:border-zinc-800 rounded-xl overflow-hidden shadow-2xl bg-white dark:bg-zinc-900">
           <div className="p-4 bg-zinc-100 dark:bg-zinc-950 border-b border-zinc-200 dark:border-zinc-800 flex items-center justify-between">
              <span className="text-xs font-mono text-zinc-500 uppercase tracking-widest">Live Demo Preview</span>
              <div className="flex gap-1.5">
                <div className="w-3 h-3 rounded-full bg-red-400"></div>
                <div className="w-3 h-3 rounded-full bg-yellow-400"></div>
                <div className="w-3 h-3 rounded-full bg-green-400"></div>
              </div>
           </div>
           
           {/* Widget Component */}
           <div className="p-0">
             <WidgetContainer />
           </div>
        </section>

        {/* Features Grid */}
        <section className="grid grid-cols-1 md:grid-cols-3 gap-8 w-full max-w-5xl mt-12">
            <div className="p-6 bg-white dark:bg-zinc-900 rounded-lg shadow-sm border border-zinc-100 dark:border-zinc-800">
                <h3 className="font-bold text-xl mb-2">Instant Analysis</h3>
                <p className="text-zinc-500 text-sm">Advanced computer vision checks your facial structure and smile characteristics in seconds.</p>
            </div>
            <div className="p-6 bg-white dark:bg-zinc-900 rounded-lg shadow-sm border border-zinc-100 dark:border-zinc-800">
                <h3 className="font-bold text-xl mb-2">AI Simulation</h3>
                <p className="text-zinc-500 text-sm">See your future smile generated by state-of-the-art Generative AI models.</p>
            </div>
            <div className="p-6 bg-white dark:bg-zinc-900 rounded-lg shadow-sm border border-zinc-100 dark:border-zinc-800">
                <h3 className="font-bold text-xl mb-2">Seamless Booking</h3>
                <p className="text-zinc-500 text-sm">Connect directly with dental professionals to turn your simulation into reality.</p>
            </div>
        </section>
      </main>

      <footer className="w-full py-8 border-t border-zinc-200 dark:border-zinc-800 text-center text-sm text-zinc-500">
        &copy; {new Date().getFullYear()} Smile Forward. Powered by Google Vertex AI & Supabase.
      </footer>
    </div>
  );
}
