-- Schema Export for project jgnvjqfvlgljmwwazmea
-- Generated by Antigravity Agent via Supabase MCP

CREATE SCHEMA IF NOT EXISTS wa;

CREATE TABLE IF NOT EXISTS public.agent_ops_audit (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    invocation_id uuid NULL ,
    tool_name text NOT NULL ,
    args jsonb NOT NULL ,
    executed_at timestamp with time zone NOT NULL DEFAULT now(),
    success boolean NOT NULL ,
    error_text text NULL ,
    contact_id uuid NULL ,
    conversation_id text NULL ,
    company_id uuid NULL ,
    agent_type text NULL ,
    result_summary jsonb NULL ,
    CONSTRAINT agent_ops_audit_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ai_chat_memory (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    session_id text NOT NULL ,
    instance_company_id uuid NOT NULL ,
    contact_id uuid NOT NULL ,
    agent_type text NOT NULL ,
    role text NOT NULL ,
    content text NOT NULL ,
    content_type text NULL DEFAULT 'message'::text,
    metadata jsonb NULL DEFAULT '{}'::jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT ai_chat_memory_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ai_chat_memory_box_v (
    session_id text NULL ,
    role text NULL ,
    message text NULL ,
    created_at timestamp with time zone NULL ,
    agent_type text NULL ,
    content_type text NULL 
);

CREATE TABLE IF NOT EXISTS public.ai_chat_memory_buffer (
    id bigint NOT NULL DEFAULT nextval('ai_chat_memory_buffer_id_seq'::regclass),
    session_id text NOT NULL ,
    message jsonb NOT NULL ,
    CONSTRAINT ai_chat_memory_buffer_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ai_chat_memory_hybrid_v (
    id text NULL ,
    session_id text NULL ,
    created_at timestamp with time zone NULL ,
    type text NULL ,
    message text NULL 
);

CREATE TABLE IF NOT EXISTS public.ai_chat_memory_hybrid_v2 (
    id text NULL ,
    session_id text NULL ,
    created_at timestamp with time zone NULL ,
    type text NULL ,
    message text NULL 
);

CREATE TABLE IF NOT EXISTS public.ai_chat_slices (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    session_id text NOT NULL ,
    instance_company_id uuid NOT NULL ,
    contact_id uuid NOT NULL ,
    agent_type text NOT NULL ,
    slice_type text NOT NULL ,
    slice_seq integer NOT NULL DEFAULT 0,
    role text NOT NULL DEFAULT 'assistant'::text,
    message_text text NOT NULL ,
    payload_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    media_meta jsonb NOT NULL DEFAULT '{}'::jsonb,
    content_type text NOT NULL DEFAULT 'slice'::text,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    cutoff_ts timestamp with time zone NOT NULL ,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT ai_chat_slices_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ai_chat_slices_memory_v (
    id text NULL ,
    session_id text NULL ,
    message jsonb NULL ,
    created_at timestamp with time zone NULL 
);

CREATE TABLE IF NOT EXISTS public.ai_chat_test (
    id integer NOT NULL DEFAULT nextval('ai_chat_test_id_seq'::regclass),
    session_id character varying NOT NULL ,
    message jsonb NOT NULL ,
    CONSTRAINT ai_chat_test_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ai_enabled (
    contact_id uuid NOT NULL ,
    company_id uuid NOT NULL ,
    ai_enabled boolean NULL DEFAULT true,
    last_updated timestamp without time zone NULL DEFAULT now(),
    updated_by text NULL DEFAULT 'system'::text,
    phone text NULL ,
    CONSTRAINT ai_enabled_pkey PRIMARY KEY (contact_id, company_id)
);

CREATE TABLE IF NOT EXISTS public.ai_memory_box_v1 (
    role text NULL ,
    content text NULL ,
    chat_timestamp timestamp with time zone NULL 
);

CREATE TABLE IF NOT EXISTS public.ai_model_policies (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    agent_type text NOT NULL ,
    provider text NOT NULL ,
    model_name text NOT NULL ,
    response_format text NOT NULL DEFAULT 'json'::text,
    tool_use boolean NOT NULL DEFAULT true,
    temperature numeric NOT NULL DEFAULT 0.20,
    top_p numeric NOT NULL DEFAULT 1.00,
    max_tokens integer NULL ,
    timeout_ms integer NULL ,
    retries integer NOT NULL DEFAULT 2,
    priority integer NOT NULL DEFAULT 100,
    active boolean NOT NULL DEFAULT true,
    notes text NULL ,
    created_by uuid NULL ,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT ai_model_policies_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ai_provider_endpoints (
    provider text NOT NULL ,
    base_url text NOT NULL ,
    endpoint_format text NOT NULL ,
    auth_style text NOT NULL ,
    api_key_env_var text NOT NULL ,
    notes text NULL ,
    CONSTRAINT ai_provider_endpoints_pkey PRIMARY KEY (provider)
);

CREATE TABLE IF NOT EXISTS public.ai_tools_library (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    tool_name character varying NOT NULL ,
    tool_description text NOT NULL ,
    function_schema jsonb NOT NULL ,
    implementation_prompt text NULL ,
    allowed_agents ARRAY NULL ,
    company_specific boolean NULL DEFAULT false,
    active boolean NULL DEFAULT true,
    user_specific boolean NULL DEFAULT false,
    CONSTRAINT ai_tools_library_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.audit_snapshots (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    batch_id uuid NOT NULL ,
    snapshot_type text NULL DEFAULT 'post_batch'::text,
    conversation_ids ARRAY NOT NULL ,
    snapshot_data jsonb NOT NULL ,
    total_conversations integer NULL ,
    total_messages integer NULL ,
    total_invocations integer NULL ,
    success_rate numeric NULL ,
    created_at timestamp with time zone NULL DEFAULT now(),
    CONSTRAINT audit_snapshots_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.banned_users (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    company_id uuid NOT NULL ,
    phone text NOT NULL ,
    reason text NULL ,
    created_at timestamp with time zone NULL DEFAULT now(),
    banned_by text NULL ,
    CONSTRAINT banned_users_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.batch_audit_summary (
    date timestamp with time zone NULL ,
    total_batches bigint NULL ,
    total_conversations bigint NULL ,
    total_successful bigint NULL ,
    total_failed bigint NULL ,
    avg_success_rate numeric NULL ,
    avg_duration_seconds numeric NULL 
);

CREATE TABLE IF NOT EXISTS public.batch_processing_audit (
    batch_id uuid NOT NULL DEFAULT gen_random_uuid(),
    batch_started_at timestamp with time zone NULL ,
    batch_finished_at timestamp with time zone NULL ,
    batch_duration_ms integer NULL ,
    total_conversations integer NOT NULL ,
    successful_sends integer NULL DEFAULT 0,
    failed_sends integer NULL DEFAULT 0,
    success_rate integer NULL DEFAULT 0,
    error_rate integer NULL DEFAULT 0,
    by_agent jsonb NULL DEFAULT '{}'::jsonb,
    by_template jsonb NULL DEFAULT '{}'::jsonb,
    by_company jsonb NULL DEFAULT '{}'::jsonb,
    conversation_ids ARRAY NULL ,
    errors_summary jsonb NULL DEFAULT '[]'::jsonb,
    created_at timestamp with time zone NULL DEFAULT now(),
    CONSTRAINT batch_processing_audit_pkey PRIMARY KEY (batch_id)
);

CREATE TABLE IF NOT EXISTS public.client_pipeline (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    company_id uuid NULL ,
    client_name character varying NOT NULL ,
    client_contact character varying NOT NULL ,
    client_company character varying NULL ,
    client_type character varying NULL ,
    stage character varying NOT NULL ,
    stage_changed_at timestamp without time zone NULL DEFAULT now(),
    estimated_value numeric NULL ,
    probability integer NULL ,
    expected_close_date date NULL ,
    next_action character varying NULL ,
    next_action_due_date timestamp without time zone NULL ,
    last_interaction timestamp without time zone NULL ,
    interaction_count integer NULL DEFAULT 0,
    assigned_to character varying NULL ,
    lead_source character varying NULL ,
    notes text NULL ,
    interaction_history jsonb NULL ,
    status character varying NULL DEFAULT 'active'::character varying,
    created_at timestamp without time zone NULL DEFAULT now(),
    updated_at timestamp without time zone NULL DEFAULT now(),
    CONSTRAINT client_pipeline_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.communication_templates (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    company_id uuid NULL ,
    template_name character varying NOT NULL ,
    template_type character varying NOT NULL ,
    template_content text NOT NULL ,
    subject_line character varying NULL ,
    variables jsonb NULL ,
    personalization_rules jsonb NULL ,
    target_audience character varying NULL ,
    use_cases ARRAY NULL ,
    usage_count integer NULL DEFAULT 0,
    success_rate numeric NULL ,
    last_used_date timestamp without time zone NULL ,
    status character varying NULL DEFAULT 'active'::character varying,
    version integer NULL DEFAULT 1,
    created_by character varying NULL ,
    approved_by character varying NULL ,
    created_at timestamp without time zone NULL DEFAULT now(),
    updated_at timestamp without time zone NULL DEFAULT now(),
    template_logic jsonb NULL ,
    variant text NOT NULL DEFAULT 'default'::text,
    variants jsonb NULL ,
    CONSTRAINT communication_templates_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.companies (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    name text NOT NULL ,
    created_at timestamp with time zone NULL DEFAULT now(),
    is_active boolean NOT NULL DEFAULT true,
    deleted_at timestamp without time zone NULL ,
    contact_phone character varying NULL ,
    contact_email text NULL ,
    escalation_phone text NULL ,
    escalation_email text NULL ,
    is_placeholder boolean NOT NULL DEFAULT false,
    company_kind text NULL DEFAULT 'business'::text,
    CONSTRAINT companies_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.companies_contact_view (
    id uuid NULL ,
    name text NULL ,
    is_active boolean NULL ,
    inactive_message text NULL 
);

CREATE TABLE IF NOT EXISTS public.company_agent_model_overrides (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    company_id uuid NOT NULL ,
    agent_type text NOT NULL ,
    policy_id uuid NOT NULL ,
    active boolean NOT NULL DEFAULT true,
    notes text NULL ,
    created_by uuid NULL ,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT company_agent_model_overrides_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.company_context (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    company_id uuid NOT NULL ,
    context_type character varying NULL ,
    context_data jsonb NOT NULL ,
    last_updated timestamp without time zone NULL DEFAULT now(),
    auth_user_id uuid NOT NULL ,
    is_onboarded boolean NULL DEFAULT false,
    context_min_summary text NULL ,
    goals_defined boolean NULL ,
    industry text NULL ,
    primary_region text NULL ,
    plan_tier text NULL ,
    business_plan jsonb NULL ,
    branding jsonb NULL ,
    marketing_plan jsonb NULL ,
    sales_plan jsonb NULL ,
    financial_plan jsonb NULL ,
    goals_okrs jsonb NULL ,
    tasks_tracking jsonb NULL ,
    min_last_updated timestamp with time zone NULL ,
    has_branding boolean NULL ,
    has_marketing boolean NULL ,
    has_sales boolean NULL ,
    ready_override boolean NULL ,
    ready_effective boolean NULL ,
    use_hybrid_architecture boolean NULL DEFAULT false,
    goals_budget_threshold numeric NULL ,
    goals_require_budget_for_company_goals boolean NULL ,
    CONSTRAINT company_context_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.company_context_audit (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    company_id uuid NOT NULL ,
    old_row jsonb NULL ,
    new_row jsonb NULL ,
    changed_at timestamp with time zone NULL DEFAULT now(),
    changed_by uuid NULL ,
    reason text NULL ,
    CONSTRAINT company_context_audit_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.company_invites (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    company_id uuid NOT NULL ,
    contact_id uuid NOT NULL ,
    token text NOT NULL ,
    role text NOT NULL ,
    permissions_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    channel text NOT NULL ,
    expires_at timestamp with time zone NOT NULL ,
    created_by uuid NOT NULL ,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    pipeline_id uuid NULL ,
    CONSTRAINT company_invites_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.company_prompts (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    company_id uuid NOT NULL ,
    agent_type text NOT NULL ,
    system_message text NULL ,
    created_at timestamp with time zone NULL DEFAULT now(),
    company_name text NULL ,
    short_message text NULL DEFAULT ''::text,
    agent_name text NULL DEFAULT 'Nova'::text,
    especializacion text NULL ,
    user_input_processing jsonb NULL ,
    tools_config jsonb NULL ,
    personality_traits jsonb NULL ,
    company_context jsonb NULL ,
    active boolean NULL DEFAULT true,
    updated_at timestamp with time zone NULL DEFAULT now(),
    tool_usage_priorities jsonb NULL ,
    default_agent_route text NULL ,
    prompt_meta jsonb NOT NULL DEFAULT '{}'::jsonb,
    version integer NOT NULL DEFAULT 1,
    policy_id uuid NULL ,
    prompt_key text NULL ,
    CONSTRAINT company_prompts_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.financial_transactions (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    contact_id uuid NOT NULL ,
    scope text NOT NULL ,
    user_company_id uuid NULL ,
    user_company_name text NULL ,
    user_company_kind text NULL ,
    transaction_type text NOT NULL ,
    date date NOT NULL ,
    amount numeric NOT NULL ,
    category text NULL ,
    payment_method text NULL ,
    description text NULL ,
    notes text NULL ,
    context_company_id uuid NOT NULL ,
    created_at timestamp with time zone NULL DEFAULT now(),
    updated_at timestamp with time zone NULL DEFAULT now(),
    created_by_agent text NULL DEFAULT 'finance'::text,
    status text NULL DEFAULT 'confirmed'::text,
    CONSTRAINT financial_transactions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.financial_transactions_log (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    raw_data jsonb NOT NULL ,
    contact_id uuid NULL ,
    context_company_id uuid NULL ,
    processed boolean NULL DEFAULT false,
    error_message text NULL ,
    created_at timestamp with time zone NULL DEFAULT now(),
    CONSTRAINT financial_transactions_log_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.financial_transactions_recent (
    id uuid NULL ,
    contact_id uuid NULL ,
    scope text NULL ,
    user_company_id uuid NULL ,
    user_company_name text NULL ,
    user_company_kind text NULL ,
    transaction_type text NULL ,
    date date NULL ,
    amount numeric NULL ,
    category text NULL ,
    payment_method text NULL ,
    description text NULL ,
    context_company_id uuid NULL ,
    created_at timestamp with time zone NULL ,
    rn bigint NULL 
);

CREATE TABLE IF NOT EXISTS public.goals (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    scope USER-DEFINED NOT NULL ,
    contact_id uuid NOT NULL ,
    context_company_id uuid NOT NULL ,
    user_company_id uuid NULL ,
    title text NOT NULL ,
    description text NULL ,
    target text NULL ,
    deadline date NULL ,
    krs jsonb NULL ,
    status text NULL DEFAULT 'active'::text,
    priority USER-DEFINED NOT NULL DEFAULT 'medium'::priority_t,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT goals_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.llm_invocations (
    invocation_id uuid NOT NULL DEFAULT gen_random_uuid(),
    conversation_id text NULL ,
    company_id uuid NULL ,
    agent_type text NULL ,
    model_provider text NULL ,
    model_name text NULL ,
    prompt_id uuid NULL ,
    prompt_version integer NULL ,
    allow_ops boolean NULL ,
    tools_effective ARRAY NULL ,
    started_at timestamp with time zone NOT NULL DEFAULT now(),
    finished_at timestamp with time zone NULL ,
    success boolean NULL ,
    error_text text NULL ,
    raw_output jsonb NULL ,
    contact_id uuid NULL ,
    latency_ms integer NULL ,
    template_used text NULL ,
    tools_executed jsonb NULL ,
    CONSTRAINT llm_invocations_pkey PRIMARY KEY (invocation_id)
);

CREATE TABLE IF NOT EXISTS public.social_content (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    company_id uuid NULL ,
    context_type character varying NOT NULL ,
    context_id uuid NULL ,
    platform character varying NOT NULL ,
    content_type character varying NOT NULL ,
    content_text text NOT NULL ,
    media_urls ARRAY NULL ,
    hashtags ARRAY NULL ,
    mentions ARRAY NULL ,
    call_to_action text NULL ,
    schedule_date timestamp without time zone NULL ,
    posted_date timestamp without time zone NULL ,
    status character varying NULL DEFAULT 'draft'::character varying,
    engagement_metrics jsonb NULL ,
    performance_score numeric NULL ,
    created_by_agent character varying NOT NULL ,
    approval_status character varying NULL DEFAULT 'pending'::character varying,
    approved_by character varying NULL ,
    content_pillar character varying NULL ,
    campaign_id uuid NULL ,
    created_at timestamp without time zone NULL DEFAULT now(),
    updated_at timestamp without time zone NULL DEFAULT now(),
    CONSTRAINT social_content_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tasks (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    goal_id uuid NULL ,
    contact_id uuid NOT NULL ,
    context_company_id uuid NOT NULL ,
    user_company_id uuid NULL ,
    task_type character varying NOT NULL ,
    title character varying NOT NULL ,
    description text NULL ,
    status character varying NULL DEFAULT 'pending'::character varying,
    priority character varying NULL DEFAULT 'medium'::character varying,
    due_date timestamp without time zone NULL ,
    estimated_duration integer NULL ,
    completion_data jsonb NULL ,
    completed_at timestamp without time zone NULL ,
    created_by character varying NOT NULL ,
    assigned_to character varying NULL ,
    parent_task_id uuid NULL ,
    related_conversation_id character varying NULL ,
    created_at timestamp without time zone NULL DEFAULT now(),
    updated_at timestamp without time zone NULL DEFAULT now(),
    scope USER-DEFINED NULL ,
    CONSTRAINT tasks_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_company_links (
    contact_id uuid NOT NULL ,
    company_id uuid NOT NULL ,
    relation text NOT NULL DEFAULT 'owner'::text,
    verified boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    permissions_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    invite_status text NOT NULL DEFAULT 'accepted'::text,
    requested_by_contact_id uuid NULL ,
    verified_by_contact_id uuid NULL ,
    verified_at timestamp with time zone NULL ,
    CONSTRAINT user_company_links_pkey PRIMARY KEY (company_id, contact_id)
);

CREATE TABLE IF NOT EXISTS public.user_context (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    contact_id uuid NOT NULL ,
    context_type text NULL ,
    context_data jsonb NOT NULL DEFAULT '{}'::jsonb,
    last_updated timestamp without time zone NULL DEFAULT now(),
    company_id uuid NULL ,
    context_min_summary text NULL ,
    is_onboarded boolean NULL ,
    goals_defined boolean NULL ,
    min_last_updated timestamp with time zone NULL ,
    language_pref text NULL ,
    timezone_pref text NULL ,
    business_context jsonb NULL ,
    personal_dev jsonb NULL ,
    wellbeing jsonb NULL ,
    goals_okrs jsonb NULL ,
    tasks_tracking jsonb NULL ,
    ready_override boolean NULL ,
    user_key text NULL ,
    ready_effective boolean NULL ,
    profile jsonb NULL ,
    preferred_name text NULL ,
    onboarding_state text NULL DEFAULT 'awaiting_initial_profile'::text,
    profile_completion_percent integer NULL DEFAULT 0,
    fallback_count integer NOT NULL DEFAULT 0,
    last_fallback_topic text NULL ,
    last_agent_handled text NULL ,
    last_fallback_at timestamp with time zone NULL ,
    personal_finance jsonb NULL DEFAULT '{}'::jsonb,
    agent_hint text NULL ,
    CONSTRAINT user_context_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_memory_snapshot (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    contact_id uuid NOT NULL ,
    company_id uuid NOT NULL ,
    memory_text text NOT NULL DEFAULT ''::text,
    profile_completion_percent integer NULL DEFAULT 0,
    goals_count integer NULL DEFAULT 0,
    last_topic text NULL DEFAULT 'onboarding'::text,
    active_goals jsonb NULL DEFAULT '[]'::jsonb,
    is_first_interaction boolean NULL DEFAULT true,
    push_name_latest text NULL ,
    message_count integer NULL DEFAULT 0,
    last_updated timestamp with time zone NULL DEFAULT now(),
    created_at timestamp with time zone NULL DEFAULT now(),
    personal_goals_count integer NULL DEFAULT 0,
    entity_goals_count integer NULL DEFAULT 0,
    entity_count integer NULL DEFAULT 0,
    has_business_context boolean NULL DEFAULT false,
    has_personal_finance boolean NULL DEFAULT false,
    CONSTRAINT user_memory_snapshot_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS wa.admins (
    auth_user_id uuid NOT NULL ,
    note text NULL ,
    created_at timestamp with time zone NULL DEFAULT now(),
    company_id uuid NOT NULL ,
    role text NOT NULL DEFAULT 'owner'::text,
    attributes jsonb NULL ,
    CONSTRAINT admins_pkey PRIMARY KEY (company_id, auth_user_id)
);

CREATE TABLE IF NOT EXISTS wa.audit_log (
    id bigint NOT NULL DEFAULT nextval('wa.audit_log_id_seq'::regclass),
    table_name text NOT NULL ,
    action text NOT NULL ,
    pk text NULL ,
    actor_uid uuid NULL ,
    actor_role text NULL ,
    actor_jwt jsonb NULL ,
    old_data jsonb NULL ,
    new_data jsonb NULL ,
    at timestamp with time zone NULL DEFAULT now(),
    company_id uuid NOT NULL ,
    CONSTRAINT audit_log_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS wa.audit_snapshot (
    source text NULL ,
    id text NULL ,
    phone text NULL ,
    chat_id text NULL ,
    push_name text NULL ,
    company_id uuid NULL ,
    contact_id uuid NULL ,
    response_status text NULL ,
    processed text NULL ,
    created_at text NULL 
);

CREATE TABLE IF NOT EXISTS wa.contacts (
    phone text NOT NULL ,
    push_name text NULL ,
    first_seen timestamp with time zone NULL DEFAULT now(),
    last_seen timestamp with time zone NULL ,
    tags ARRAY NULL DEFAULT '{}'::text[],
    attributes jsonb NULL DEFAULT '{}'::jsonb,
    notes text NULL ,
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    trial_started_at timestamp with time zone NULL DEFAULT now(),
    trial_days integer NULL ,
    company_id uuid NOT NULL ,
    nickname text NULL ,
    real_name text NULL ,
    user_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000'::uuid,
    alternative_chat_id text NULL ,
    CONSTRAINT contacts_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS wa.index_usage_snapshot (
    snapshot_id uuid NOT NULL DEFAULT gen_random_uuid(),
    index_name text NOT NULL ,
    idx_scan bigint NULL ,
    idx_tup_read bigint NULL ,
    idx_tup_fetch bigint NULL ,
    snapshot_time timestamp with time zone NULL DEFAULT now(),
    CONSTRAINT index_usage_snapshot_pkey PRIMARY KEY (snapshot_id)
);

CREATE TABLE IF NOT EXISTS wa.membership_plans (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    company_id uuid NOT NULL ,
    name text NOT NULL ,
    description text NULL ,
    price numeric NULL ,
    duration_days integer NULL ,
    attributes jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp with time zone NULL DEFAULT now(),
    features_enabled jsonb NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT membership_plans_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS wa.membership_status_v2 (
    contact_id uuid NULL ,
    phone text NULL ,
    company_id uuid NULL ,
    push_name text NULL ,
    nickname text NULL ,
    real_name text NULL ,
    membership_id uuid NULL ,
    plan_id uuid NULL ,
    plan_name text NULL ,
    price numeric NULL ,
    duration_days integer NULL ,
    started_at timestamp with time zone NULL ,
    expires_at timestamp with time zone NULL ,
    membership_state text NULL ,
    days_left integer NULL ,
    effective_status text NULL 
);

CREATE TABLE IF NOT EXISTS wa.memberships (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    contact_id uuid NULL ,
    plan text NOT NULL ,
    started_at timestamp with time zone NULL DEFAULT now(),
    expires_at timestamp with time zone NOT NULL ,
    status text NULL DEFAULT 'active'::text,
    notes text NULL ,
    company_id uuid NOT NULL ,
    plan_id uuid NULL ,
    attributes jsonb NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT memberships_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS wa.wa_consolidated (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    phone text NOT NULL ,
    chat_id text NULL ,
    content text NULL ,
    media jsonb NULL ,
    timestamp timestamp with time zone NOT NULL DEFAULT now(),
    incoming_ids ARRAY NULL ,
    ai_status text NOT NULL DEFAULT 'pending'::text,
    created_at timestamp with time zone NULL DEFAULT now(),
    instance_id uuid NULL ,
    company_id uuid NOT NULL ,
    contact_id uuid NULL ,
    message_ids ARRAY NULL ,
    conversation_id text NULL ,
    role text NULL DEFAULT 'user'::text,
    agent_action text NULL ,
    agent_type text NULL ,
    agent_timestamp timestamp with time zone NULL ,
    client_timestamp timestamp with time zone NULL ,
    agent_summary text NULL ,
    was_summarized boolean NULL DEFAULT false,
    token_count integer NULL ,
    CONSTRAINT wa_consolidated_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS wa.wa_incoming (
    message_id text NOT NULL ,
    phone text NULL ,
    chat_id text NULL ,
    instance text NULL ,
    push_name text NULL ,
    content text NULL ,
    content_original text NULL ,
    has_url boolean NULL DEFAULT false,
    urls ARRAY NULL ,
    message_type text NULL ,
    media_type text NULL ,
    media_url text NULL ,
    base64 text NULL ,
    media_key text NULL ,
    file_sha256 text NULL ,
    file_enc_sha256 text NULL ,
    raw_payload jsonb NULL ,
    processed boolean NULL DEFAULT false,
    processed_at timestamp with time zone NULL ,
    response_text text NULL ,
    response_status text NULL ,
    ai_intent text NULL ,
    latency_ms integer NULL ,
    error_text text NULL ,
    created_at timestamp with time zone NULL DEFAULT now(),
    manual_ai_intent text NULL ,
    manual_notes text NULL ,
    contact_id uuid NULL ,
    company_id uuid NULL ,
    ingested boolean NULL DEFAULT false,
    ingested_at timestamp with time zone NULL ,
    processing_error text NULL ,
    sender_phone text NULL ,
    instance_id uuid NULL ,
    consolidated text NULL DEFAULT 'pending'::text,
    current_status text NULL ,
    conversation_id text NULL ,
    role text NULL ,
    updated_at timestamp with time zone NULL ,
    CONSTRAINT wa_incoming_pkey PRIMARY KEY (message_id)
);

CREATE TABLE IF NOT EXISTS wa.wa_instances (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    company_id uuid NOT NULL ,
    phone_number text NOT NULL ,
    wa_token text NOT NULL ,
    attributes jsonb NULL DEFAULT '{}'::jsonb,
    created_at timestamp with time zone NULL DEFAULT now(),
    instance_name text NULL ,
    CONSTRAINT wa_instances_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS wa.wa_outgoing (
    message_id text NOT NULL ,
    phone text NULL ,
    chat_id text NULL ,
    instance text NULL ,
    content text NULL ,
    media_url text NULL ,
    status text NULL ,
    error_text text NULL ,
    created_at timestamp with time zone NULL DEFAULT now(),
    sent_at timestamp with time zone NULL ,
    company_id uuid NULL ,
    contact_id uuid NULL ,
    CONSTRAINT wa_outgoing_pkey PRIMARY KEY (message_id)
);

-- Foreign Keys
ALTER TABLE public.agent_ops_audit ADD CONSTRAINT agent_ops_audit_invocation_id_fkey FOREIGN KEY (invocation_id) REFERENCES public.llm_invocations (invocation_id);
ALTER TABLE public.ai_chat_memory ADD CONSTRAINT ai_chat_memory_instance_company_id_fkey FOREIGN KEY (instance_company_id) REFERENCES public.companies (id);
ALTER TABLE public.audit_snapshots ADD CONSTRAINT fk_batch FOREIGN KEY (batch_id) REFERENCES public.batch_processing_audit (batch_id);
ALTER TABLE public.banned_users ADD CONSTRAINT banned_users_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies (id);
ALTER TABLE public.client_pipeline ADD CONSTRAINT client_pipeline_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies (id);
ALTER TABLE public.communication_templates ADD CONSTRAINT communication_templates_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies (id);
ALTER TABLE public.company_agent_model_overrides ADD CONSTRAINT company_agent_model_overrides_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies (id);
ALTER TABLE public.company_agent_model_overrides ADD CONSTRAINT company_agent_model_overrides_policy_id_fkey FOREIGN KEY (policy_id) REFERENCES public.ai_model_policies (id);
ALTER TABLE public.company_context ADD CONSTRAINT fk_company_context_company FOREIGN KEY (company_id) REFERENCES public.companies (id);
ALTER TABLE public.company_invites ADD CONSTRAINT company_invites_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies (id);
ALTER TABLE public.company_invites ADD CONSTRAINT company_invites_pipeline_id_fkey FOREIGN KEY (pipeline_id) REFERENCES public.client_pipeline (id);
ALTER TABLE public.company_prompts ADD CONSTRAINT company_prompts_policy_id_fkey FOREIGN KEY (policy_id) REFERENCES public.ai_model_policies (id);
ALTER TABLE public.financial_transactions ADD CONSTRAINT financial_transactions_context_company_id_fkey FOREIGN KEY (context_company_id) REFERENCES public.companies (id);
ALTER TABLE public.goals ADD CONSTRAINT fk_goals_context_company FOREIGN KEY (context_company_id) REFERENCES public.companies (id);
ALTER TABLE public.goals ADD CONSTRAINT fk_goals_user_company FOREIGN KEY (user_company_id) REFERENCES public.companies (id);
ALTER TABLE public.social_content ADD CONSTRAINT social_content_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies (id);
ALTER TABLE public.tasks ADD CONSTRAINT fk_tasks_context_company FOREIGN KEY (context_company_id) REFERENCES public.companies (id);
ALTER TABLE public.tasks ADD CONSTRAINT fk_tasks_parent_task FOREIGN KEY (parent_task_id) REFERENCES public.tasks (id);
ALTER TABLE public.tasks ADD CONSTRAINT fk_tasks_goal FOREIGN KEY (goal_id) REFERENCES public.goals (id);
ALTER TABLE public.tasks ADD CONSTRAINT fk_tasks_user_company FOREIGN KEY (user_company_id) REFERENCES public.companies (id);
ALTER TABLE public.user_context ADD CONSTRAINT fk_user_context_company FOREIGN KEY (company_id) REFERENCES public.companies (id);
ALTER TABLE wa.memberships ADD CONSTRAINT memberships_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES wa.contacts (id);
ALTER TABLE wa.memberships ADD CONSTRAINT memberships_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES wa.membership_plans (id);
ALTER TABLE wa.wa_incoming ADD CONSTRAINT fk_instance FOREIGN KEY (instance_id) REFERENCES wa.wa_instances (id);
ALTER TABLE wa.wa_incoming ADD CONSTRAINT fk_wa_incoming_contacts FOREIGN KEY (contact_id) REFERENCES wa.contacts (id);
ALTER TABLE wa.wa_outgoing ADD CONSTRAINT wa_outgoing_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES wa.contacts (id);

-- Functions
-- Triggers
CREATE TRIGGER trg_membership_plans_default_features BEFORE INSERT OR UPDATE OF name, features_enabled ON wa.membership_plans FOR EACH ROW EXECUTE FUNCTION wa.tg_membership_plans_default_features();

CREATE TRIGGER audit_company_context AFTER INSERT OR UPDATE ON public.company_context FOR EACH ROW EXECUTE FUNCTION trg_audit_company_context();

CREATE TRIGGER trg_memberships_biur_set_company BEFORE INSERT OR UPDATE OF contact_id ON wa.memberships FOR EACH ROW EXECUTE FUNCTION wa.tg_memberships_biur_set_company();

CREATE TRIGGER trg_company_trial_plan AFTER INSERT ON wa.admins FOR EACH ROW EXECUTE FUNCTION wa.create_company_trial_plan();

CREATE TRIGGER trg_company_create_trial_plan AFTER INSERT ON public.companies FOR EACH ROW EXECUTE FUNCTION wa.tg_company_create_trial_plan();

CREATE TRIGGER trg_contact_create_trial_membership AFTER INSERT ON wa.contacts FOR EACH ROW EXECUTE FUNCTION wa.tg_contact_create_trial_membership();

CREATE TRIGGER trg_financial_transactions_updated_at BEFORE UPDATE ON public.financial_transactions FOR EACH ROW EXECUTE FUNCTION update_financial_transactions_updated_at();

CREATE TRIGGER trg_user_context_preferred_name BEFORE INSERT OR UPDATE OF profile, preferred_name ON public.user_context FOR EACH ROW EXECUTE FUNCTION tg_compute_user_preferred_name();

CREATE TRIGGER trg_bump_min_last_updated_company BEFORE INSERT OR UPDATE ON public.company_context FOR EACH ROW EXECUTE FUNCTION compute_ready_and_bump_min_last_updated();

CREATE TRIGGER trg_company_context_touch BEFORE UPDATE OF context_data, business_plan, branding, marketing_plan, sales_plan, financial_plan, goals_okrs, tasks_tracking, industry, primary_region, plan_tier, context_min_summary, ready_override ON public.company_context FOR EACH ROW EXECUTE FUNCTION tg_touch_last_updated();

CREATE TRIGGER trg_bump_min_last_updated_user BEFORE INSERT OR UPDATE ON public.user_context FOR EACH ROW EXECUTE FUNCTION compute_ready_and_bump_min_last_updated();

CREATE TRIGGER trg_user_context_touch BEFORE UPDATE OF context_data, business_context, personal_dev, wellbeing, goals_okrs, tasks_tracking, language_pref, timezone_pref, profile, preferred_name, context_min_summary, ready_override, onboarding_state ON public.user_context FOR EACH ROW EXECUTE FUNCTION tg_touch_last_updated();

CREATE TRIGGER trigger_update_profile_completion BEFORE INSERT OR UPDATE OF profile ON public.user_context FOR EACH ROW EXECUTE FUNCTION update_profile_completion();

CREATE TRIGGER trg_goals_touch BEFORE UPDATE ON public.goals FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE TRIGGER trg_tasks_touch BEFORE UPDATE ON public.tasks FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

