
import { createClient } from '@supabase/supabase-js';
import * as dotenv from 'dotenv';

dotenv.config({ path: '.env.local' });
dotenv.config({ path: '.env.production' });
dotenv.config({ path: '.env' });

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseKey) {
    console.error("❌ Missing Supabase environment variables.");
    process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

async function seedData() {
    console.log("🌱 Seeding Test Data...");

    // 1. Insert a Test Lead
    const leadData = {
        name: "Usuario de Prueba",
        email: `test_${Date.now()}@example.com`,
        phone: "+56912345678",
        status: "pending",
        survey_data: { note: "Generated by seed script" }
    };

    const { error: leadError } = await supabase
        .from('leads')
        .insert(leadData);

    if (leadError) {
        console.error("❌ Error inserting lead:", leadError.message);
    } else {
        console.log("✅ Lead inserted (Blind insert for security).");
    }

    // 2. Insert a Log Entry
    const { error: logError } = await supabase
        .from('audit_logs')
        .insert({
            action: 'TEST_SEED',
            details: { message: 'Test data injected manually' },
            user_id: 'seed_script_user'
        });

    if (logError) {
        console.error("❌ Error inserting log:", logError.message);
    } else {
        console.log("✅ Audit log entry created.");
    }

    console.log("🎉 Seeding complete! Check your Dashboard.");
}

seedData();
